"use client";

import { useMemo, useState } from "react";
import { formatMoney } from "@/lib/format";

export interface PaidInvoice {
  /** ISO timestamp of when it was marked paid. */
  paidAt: string;
  amount: number;
}

const RANGES = [
  { months: 3, label: "3 months" },
  { months: 6, label: "6 months" },
  { months: 12, label: "12 months" },
  { months: 24, label: "2 years" },
] as const;

const STORAGE_KEY = "advatar-revenue-range";

/**
 * Money actually received, by month.
 *
 * Every bucket is generated by counting backwards from the current
 * month at render time — there are no hardcoded years, month names or
 * date boundaries anywhere in here, so this keeps working indefinitely
 * without anyone editing it. Adding a longer range is one line in
 * RANGES above.
 *
 * It plots paid invoices rather than recurring value on purpose: this
 * is what landed in the account, not what was promised. Recurring
 * value is shown separately as its own figure.
 */
export function RevenueChart({ invoices }: { invoices: PaidInvoice[] }) {
  const [months, setMonths] = useState<number>(() => {
    try {
      const saved = Number(window.localStorage.getItem(STORAGE_KEY));
      return RANGES.some((r) => r.months === saved) ? saved : 6;
    } catch {
      return 6;
    }
  });

  function chooseRange(next: number) {
    setMonths(next);
    try {
      window.localStorage.setItem(STORAGE_KEY, String(next));
    } catch {
      /* not worth breaking the page over */
    }
  }

  const buckets = useMemo(() => {
    const now = new Date();
    // Anchor on the first of the current month, then walk backwards.
    // Using date arithmetic rather than fixed month lengths means
    // year boundaries and leap years look after themselves.
    const out: { key: string; label: string; short: string; total: number }[] = [];

    for (let i = months - 1; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      out.push({
        key: `${d.getFullYear()}-${d.getMonth()}`,
        label: d.toLocaleDateString("en-GB", { month: "long", year: "numeric" }),
        short: d.toLocaleDateString("en-GB", { month: "short" }),
        total: 0,
      });
    }

    const index = new Map(out.map((b, i) => [b.key, i]));

    for (const invoice of invoices) {
      const d = new Date(invoice.paidAt);
      if (Number.isNaN(d.getTime())) continue;
      const slot = index.get(`${d.getFullYear()}-${d.getMonth()}`);
      if (slot !== undefined) out[slot].total += invoice.amount;
    }

    return out;
  }, [invoices, months]);

  const max = Math.max(...buckets.map((b) => b.total), 1);
  const total = buckets.reduce((sum, b) => sum + b.total, 0);
  const average = total / buckets.length;

  // Wider ranges need narrower bars, or two years of them won't fit.
  const barMinWidth = months > 12 ? 22 : months > 6 ? 34 : 52;

  return (
    <div>
      <div className="filter-bar" style={{ marginBottom: 14 }}>
        {RANGES.map((r) => (
          <button
            key={r.months}
            type="button"
            className={months === r.months ? "btn btn-primary" : "btn"}
            onClick={() => chooseRange(r.months)}
            aria-pressed={months === r.months}
            style={{ minHeight: 38, padding: "8px 14px" }}
          >
            {r.label}
          </button>
        ))}
        <span className="filter-count">
          {formatMoney(total)} in · {formatMoney(average)}/mo average
        </span>
      </div>

      <div
        className="scroll-x"
        style={{
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-md)",
          background: "var(--surface)",
          boxShadow: "var(--shadow-sm)",
          padding: "24px 22px 16px",
          position: "relative",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "flex-end",
            gap: 6,
            height: 190,
            minWidth: buckets.length * (barMinWidth + 6),
          }}
        >
          {buckets.map((b) => {
            const heightPct = max > 0 ? (b.total / max) * 100 : 0;
            return (
              <div
                key={b.key}
                style={{
                  flex: 1,
                  minWidth: barMinWidth,
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "flex-end",
                  height: "100%",
                }}
                title={`${b.label}: ${formatMoney(b.total)}`}
              >
                {/* The figure sits above its own bar rather than in a
                    tooltip — this gets read on a phone, where there is
                    no hover. */}
                <span
                  style={{
                    fontFamily: "var(--font-mono)",
                    fontSize: 9.5,
                    color: b.total === max && b.total > 0 ? "var(--accent)" : b.total > 0 ? "var(--text-2)" : "var(--text-3)",
                    textAlign: "center",
                    marginBottom: 4,
                    fontVariantNumeric: "tabular-nums",
                    whiteSpace: "nowrap",
                  }}
                >
                  {b.total > 0 ? formatMoney(b.total) : "—"}
                </span>
                {/* The best month in the range is the only bar that
                    takes the accent. Colouring all of them the same
                    strength would say nothing; colouring one says
                    "this is the month to look at". */}
                <div
                  style={{
                    height: `${Math.max(heightPct, b.total > 0 ? 3 : 1)}%`,
                    background:
                      b.total <= 0
                        ? "var(--chart-track)"
                        : b.total === max
                        ? "var(--accent)"
                        : "var(--chart-2)",
                    opacity: b.total > 0 && b.total !== max ? 0.75 : 1,
                    borderRadius: "var(--radius-xs) var(--radius-xs) 2px 2px",
                    minHeight: 2,
                    transition: "height 0.3s ease",
                  }}
                />
              </div>
            );
          })}
        </div>

        <div
          style={{
            display: "flex",
            gap: 6,
            marginTop: 8,
            minWidth: buckets.length * (barMinWidth + 6),
          }}
        >
          {buckets.map((b, i) => (
            <span
              key={b.key}
              style={{
                flex: 1,
                minWidth: barMinWidth,
                fontFamily: "var(--font-mono)",
                fontSize: 9.5,
                color: "var(--text-3)",
                textAlign: "center",
                whiteSpace: "nowrap",
              }}
            >
              {/* On the longest range, label every other month so they
                  don't collide. */}
              {months > 12 && i % 2 === 1 ? "" : b.short}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
