import type { MetadataRoute } from "next";

/**
 * What a phone reads when someone taps "Add to Home Screen".
 *
 * `display: "standalone"` is the point of the exercise: the CRM opens
 * without Safari's or Chrome's chrome around it, so it behaves like an
 * app rather than a bookmark.
 *
 * Two flavours of icon, because Android and iOS crop differently:
 *
 *   "any"      — used as drawn. iOS rounds the corners itself and
 *                nothing is lost.
 *   "maskable" — Android crops to whatever shape the launcher uses
 *                (circle, squircle, teardrop) and only guarantees the
 *                middle 80%. Ours keeps the A well inside that, so no
 *                launcher clips it.
 *
 * Both are generated by scripts/generate-app-icons.py from the "A"
 * mark; re-run it if the mark ever changes.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Advatar CRM",
    short_name: "Advatar",
    description: "Clients, content plans and schedules for Advatar Marketing.",
    // Straight to the login gate, which forwards each role to its own
    // home — so the icon lands people where they actually work.
    start_url: "/app",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#181818",
    theme_color: "#181818",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-256.png", sizes: "256x256", type: "image/png", purpose: "any" },
      { src: "/icons/icon-384.png", sizes: "384x384", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
